#ifndef AVR_I2C_LED_MATRIX
#define AVR_I2C_LED_MATRIX

#define AVR_I2C_CMD_FRAMEBUFFER 0x00
#define AVR_I2C_CMD_INTENSITY_LOW 0x01
#define AVR_I2C_CMD_INTENSITY_HIGH 0x02

#define AVR_I2C_CMD_NONE 0xFF

#define AVR_I2C_NUM_LEVELS 8

#endif
